- color: D73A4A
  description: Pull request requires documentation updates
  name: 'docs: needed'
- color: 0E8A16
  description: Pull request does not require documentation changes
  name: 'docs: skip'
