- color: A93226
  description: Breaking changes which can be included in a major release only
  name: 'semver: major'
- color: E78F1F
  description: Non-breaking changes which can be included in minor releases, but not in patch releases
  name: 'semver: minor'
- color: 2ECC71
  description: Non-breaking changes which can be included in patch releases
  name: 'semver: patch'
