- color: ff9900
  description: AWS Account Management
  name: aws:account
- color: ff9900
  description: AWS Certificate Manager
  name: aws:acm
- color: ff9900
  description: AWS ACM Private Certificate Authority
  name: aws:acm-pca
- color: ff9900
  description: AWS Amplify
  name: aws:amplify
- color: ff9900
  description: Amazon API Gateway
  name: aws:apigateway
- color: ff9900
  description: Amazon API Gateway v2
  name: aws:apigatewayv2
- color: ff9900
  description: AWS AppConfig
  name: aws:appconfig
- color: ff9900
  description: AWS Application Auto Scaling
  name: aws:applicationautoscaling
- color: ff9900
  description: AWS AppSync
  name: aws:appsync
- color: ff9900
  description: Amazon Athena
  name: aws:athena
- color: ff9900
  description: AWS EC2 Auto Scaling
  name: aws:autoscaling
- color: ff9900
  description: AWS Backup
  name: aws:backup
- color: ff9900
  description: AWS Batch
  name: aws:batch
- color: ff9900
  description: AWS Cost Explorer 
  name: aws:ce
- color: ff9900
  description: AWS CloudFormation
  name: aws:cloudformation
- color: ff9900
  description: Amazon CloudFront
  name: aws:cloudfront
- color: ff9900
  description: Amazon CloudSearch
  name: aws:cloudsearch
- color: ff9900
  description: AWS CloudTrail
  name: aws:cloudtrail
- color: ff9900
  description: Amazon CloudWatch
  name: aws:cloudwatch
- color: ff9900
  description: AWS CodeCommit
  name: aws:codecommit
- color: ff9900
  description: AWS CodePipeline
  name: aws:codepipeline
- color: ff9900
  description: Amazon Cognito
  name: aws:cognito
- color: ff9900
  description: AWS Config
  name: aws:config
- color: ff9900
  description: AWS Database Migration Service
  name: aws:dms
- color: ff9900
  description: Amazon DocumentDB
  name: aws:docdb
- color: ff9900
  description: Amazon DynamoDB
  name: aws:dynamodb
- color: ff9900
  description: AWS DynamoDB Streams
  name: aws:dynamodbstreams
- color: ff9900
  description: Amazon Elastic Compute Cloud
  name: aws:ec2
- color: ff9900
  description: Amazon Elastic Container Registry
  name: aws:ecr
- color: ff9900
  description: Amazon Elastic Container Service
  name: aws:ecs
- color: ff9900
  description: Amazon Elastic File System
  name: aws:efs
- color: ff9900
  description: Amazon Elastic Kubernetes Service
  name: aws:eks
- color: ff9900
  description: Amazon ElastiCache
  name: aws:elasticache
- color: ff9900
  description: AWS Elastic Beanstalk
  name: aws:elasticbeanstalk
- color: ff9900
  description: Amazon Elastic Transcoder
  name: aws:elastictranscoder
- color: ff9900
  description: AWS Elastic Load Balancer
  name: aws:elb
- color: ff9900
  description: AWS Elastic Load Balancer v2
  name: aws:elbv2
- color: ff9900
  description: Amazon Elastic Map Reduce
  name: aws:emr
- color: ff9900
  description: AWS Elasticsearch
  name: aws:es
- color: ff9900
  description: Amazon EventBridge
  name: aws:events
- color: ff9900
  description: AWS Fargate
  name: aws:fargate
- color: ff9900
  description: Amazon Data Firehose
  name: aws:firehose
- color: ff9900
  description: AWS Fault Injection Service
  name: aws:fis
- color: ff9900
  description: Amazon S3 Glacier
  name: aws:glacier
- color: ff9900
  description: AWS Glue
  name: aws:glue
- color: ff9900
  description: AWS Identity and Access Management
  name: aws:iam
- color: ff9900
  description: AWS IAM Identity Store
  name: aws:identitystore
- color: ff9900
  description: AWS IoT Core
  name: aws:iot
- color: ff9900
  description: AWS IoT Analytics
  name: aws:iotanalytics
- color: ff9900
  description: AWS IoT Wireless
  name: aws:iotwireless
- color: ff9900
  description: Amazon VPC IP Address Manager
  name: aws:ipam
- color: ff9900
  description: Amazon Managed Streaming for Apache Kafka
  name: aws:kafka
- color: ff9900
  description: Amazon Kinesis
  name: aws:kinesis
- color: ff9900
  description: Amazon Kinesis Analytics
  name: aws:kinesisanalytics
- color: ff9900
  description: Amazon Kinesis Analytics v2
  name: aws:kinesisanalyticsv2
- color: ff9900
  description: AWS Key Management Service
  name: aws:kms
- color: ff9900
  description: AWS Lambda
  name: aws:lambda
- color: ff9900
  description: AWS CloudWatch Logs
  name: aws:logs
- color: ff9900
  description: Amazon Managed Blockchain
  name: aws:managedblockchain
- color: ff9900
  description: AWS Elemental Media Store
  name: aws:mediastore
- color: ff9900
  description: Amazon MemoryDB for Redis
  name: aws:memorydb
- color: ff9900
  description: Amazon MQ
  name: aws:mq
- color: ff9900
  description: Amazon Managed Workflows for Apache Airflow
  name: aws:mwaa
- color: ff9900
  description: Amazon Neptune
  name: aws:neptune
- color: ff9900
  description: Amazon OpenSearch Service
  name: aws:opensearch
- color: ff9900
  description: AWS Organizations
  name: aws:organizations
- color: ff9900
  description: Amazon Pinpoint
  name: aws:pinpoint
- color: ff9900
  description: Amazon EventBridge Pipes
  name: aws:pipes
- color: ff9900
  description: Amazon Quantum Ledger Database
  name: aws:qldb
- color: ff9900
  description: AWS Resource Access Manager
  name: aws:ram
- color: ff9900
  description: Amazon Relational Database Service
  name: aws:rds
- color: ff9900
  description: Amazon Redshift
  name: aws:redshift
- color: ff9900
  description: AWS Resource Groups
  name: aws:resourcegroups
- color: ff9900
  description: Amazon Route 53
  name: aws:route53
- color: ff9900
  description: Amazon Route 53 Resolver
  name: aws:route53resolver
- color: ff9900
  description: Amazon Simple Storage Service
  name: aws:s3
- color: ff9900
  description: Amazon SageMaker
  name: aws:sagemaker
- color: ff9900
  description: Amazon EventBridge Scheduler
  name: aws:scheduler
- color: ff9900
  description: AWS Secrets Manager
  name: aws:secretsmanager
- color: ff9900
  description: AWS Serverless Application Repository
  name: aws:serverlessrepo
- color: ff9900
  description: AWS Cloud Map
  name: aws:servicediscovery
- color: ff9900
  description: AWS Service Quotas
  name: aws:servicequotas
- color: ff9900
  description: Amazon Simple Email Service
  name: aws:ses
- color: ff9900
  description: Amazon Simple Email Service v2
  name: aws:sesv2
- color: ff9900
  description: Amazon Simple Notification Service
  name: aws:sns
- color: ff9900
  description: Amazon Simple Queue Service
  name: aws:sqs
- color: ff9900
  description: AWS Systems Manager
  name: aws:ssm
- color: F0AE3E
  description: AWS IAM Identity Centre
  name: aws:sso-admin
- color: ff9900
  description: AWS Step Functions
  name: aws:stepfunctions
- color: ff9900
  description: AWS Security Token Service
  name: aws:sts
- color: ff9900
  description: AWS Support
  name: aws:support
- color: ff9900
  description: Amazon Simple Workflow Service
  name: aws:swf
- color: ff9900
  description: Amazon Textract
  name: aws:textract
- color: ff9900
  description: Amazon Timestream
  name: aws:timestream
- color: ff9900
  description: Amazon Transcribe
  name: aws:transcribe
- color: ff9900
  description: AWS Transfer Family
  name: aws:transfer
- color: ff9900
  description: AWS Web Application Firewall
  name: aws:wafv2
- color: ff9900
  description: AWS X-Ray
  name: aws:xray
