- color: C2FF99
  description: The feature/enhancement request was accepted
  name: 'status: accepted'
- color: D38C02
  description: The issue has been triaged but not yet being worked on
  name: 'status: backlog'
- color: C2FF99
  description: The bug report was confirmed
  name: 'status: confirmed'
- color: F07333
  description: An issue is currently being worked on
  name: 'status: in progress'
- color: 0052CC
  description: The issue is resolved by providing a fix/implementation
  name: 'status: resolved/fixed'
- color: E5E5E5
  description: Closed due to staleness
  name: 'status: resolved/stale'
- color: 0052CC
  description: The issue is resolved by providing a workaround
  name: 'status: resolved/workaround'
- color: FFF799
  description: Waiting for a response from the reporter
  name: 'status: response required'
- color: E5E5E5
  description: Will be closed soon due to staleness
  name: 'status: stale'
- color: ffbb99
  description: LocalStack maintainers need to evaluate this issue
  name: 'status: triage needed'
