name: debug enforce labels

run-name: Label Enforcement
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  name: Label Check
  labels:
    uses: localstack/meta/.github/workflows/pr-enforce-label-groups.yml@aidehn/feat/calendar-versioning-migrations-and-cleanup
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}