name: debug enforce labels
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  labels:
    uses: localstack/meta/.github/workflows/pr-enforce-label-groups.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}