# Ensures all the relevant groups of labels are applied to a PR.
name: Enforce All PR Labels

on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub personal access token with write access to the project

jobs:
  calver-labels:
    uses: localstack/meta/.github/workflows/pr-enforce-calver-labels.yml@main
    secrets:
      github-token: ${{ secrets.github-token }}

  docs-labels:
    uses: localstack/meta/.github/workflows/pr-enforce-docs-labels.yml@main
    secrets:
      github-token: ${{ secrets.github-token }}

  notes-labels:
    uses: localstack/meta/.github/workflows/pr-enforce-notes-labels.yml@main
    secrets:
      github-token: ${{ secrets.github-token }}