on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub personal access token with write access to the project

jobs:
  enforce-docs-label:
    uses: localstack/meta/.github/workflows/pr-enforce-pr-labels.yml@main
    with:
      labels: "docs: needed, docs: skip"
    secrets:
      github-token: ${{ secrets.github-token }}
