name: Enforce SemVer labels

on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub personal access token with write access to the project

jobs:
  add-to-project:
    name: Add to project
    uses: localstack/meta/.github/workflows/pr-enforce-pr-labels.yml@main
    with:
      labels: "semver: patch, semver: minor, semver: major"
    secrets:
      github-token: ${{ secrets.github-token }}