name: Enforce no Breaking Changes

on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub token with access to the issues of the calling repo

jobs:
  enforce-no-breaking-changes:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "calver: breaking, semver: major"
          add_comment: true
          token: ${{ secrets.github-token }}
          message: "Currently, no breaking changes are allowed on main. Your PR labels ({{ applied }}) indicate that it cannot be merged into the main at this time."
