name: Enforce labels

on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub personal access token with write access to the project

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: semver
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver: patch, semver: minor, semver: major"
          add_comment: true
          token: ${{ secrets.github-token }}

      - name: docs
        uses: mheap/github-action-required-labels@v5
        if: '!cancelled()'
        with:
          mode: exactly
          count: 1
          labels: "docs: needed, docs: skip"
          add_comment: true
          token: ${{ secrets.github-token }}

      - name: notes
        uses: mheap/github-action-required-labels@v5
        if: '!cancelled()'
        with:
          mode: exactly
          count: 1
          labels: "notes: needed, notes: skip"
          add_comment: true
          token: ${{ secrets.github-token }}