name: Enforce PR labels

on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: A GitHub personal access token with write access to the project

jobs:
  calver:
    name: Calendar Versioning Labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "calver: patch, calver: monthly, calver: breaking"
          token: ${{ secrets.github-token }}

  docs:
    name: Documentation Labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "docs: needed, docs: skip"
          token: ${{ secrets.github-token }}

  notes:
    name: Notes Labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "notes: needed, notes: skip"
          token: ${{ secrets.github-token }}
