name: Validate feature catalog files

on:
  workflow_call:
    inputs:
      aws_services_path:
        description: 'Directory containing AWS service implementations in the localstack repository'
        type: string
        required: true
      localstack_meta_ref:
        description: 'Branch to checkout in the localstack/meta repository without "origin/" prefix'
        type: string
        required: false

jobs:
  validate-features-files:
    name: Validate feature catalog files
    runs-on: ubuntu-latest

    steps:
      # Clone repository that's calling this reusable workflow
      - name: Checkout current repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      # Clone the localstack/meta repo to access required Python scripts and JSON schema files
      - name: Checkout localstack/meta repository
        uses: actions/checkout@v5
        with:
          repository: 'localstack/meta'
          sparse-checkout: |
            .github/scripts
            .github/features_schema.json
          ref: ${{ inputs.localstack_meta_ref || 'main' }}
          path: 'localstack-meta'

      - name: Fetch list of modified files in the PR
        id: changed-files
        run: |
          ALL_CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r \
            --diff-filter=AM ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | paste -sd "," -)
          echo "all_changed_files=$ALL_CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install pyyaml jsonschema

      - name: Check features files exist
        env:
          ALL_CHANGED_FILES: "${{ steps.changed-files.outputs.all_changed_files }}"
          SERVICES_PATH: "${{ inputs.aws_services_path }}"
        run: python3 localstack-meta/.github/scripts/check_features_files_exist.py

      - name: Validate features files
        env:
          ALL_CHANGED_FILES: "${{ steps.changed-files.outputs.all_changed_files }}"
          FEATURES_JSON_SCHEMA: 'localstack-meta/.github/features_schema.json'
        run: python3 localstack-meta/.github/scripts/validate_features_files.py
