name: Validate feature catalog files

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'To manually launch this workflow, provide the PR number'
        type: number
        required: false
      localstack_meta_ref:
        description: 'To manually launch this workflow, provide branch to checkout in the localstack/meta'
        type: string
        required: false

jobs:
  validate-features-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout localstack/meta repository
        uses: actions/checkout@v4
        with:
          repository: 'localstack/meta'
          sparse-checkout: |
            .github/scripts
            .github/features_schema.json
          ref: ${{ github.event.inputs.localstack_meta_ref || 'main' }}
          path: 'localstack-meta'

      - name: Fetch list of modified files in the PR
        id: changed-files
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
        run: |
          ALL_CHANGED_FILES=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files" | jq -r '.[].filename' | paste -sd, -)
          echo "all_changed_files=$ALL_CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install pyyaml jsonschema

      - name: Validate features files
        env:
          ALL_CHANGED_FILES: "${{ steps.changed-files.outputs.all_changed_files }}"
          FEATURES_JSON_SCHEMA: 'localstack-meta/.github/features_schema.json'
        run: python3 localstack-meta/.github/scripts/validate_features_files.py
